language: python
python:
  - 2.7
  - 3.6
sudo: required
install:
  - sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - cd $HOME/build/paninski-lab/yass/yass
  - pip install .
  - pytest
after_success: coveralls