clean_up:
  abs_max_diff: 1.5
  mad:
    max_violations: 10
    min_var_gap: 2
  min_fr: 0.2
  min_ptp: 2.5
  off_center: 5
  rel_max_diff: 0.1
cluster:
  knn_triage: 0.05
  max_n_spikes: 10000
  min_fr: 0.2
  prior:
    V: 2
    a: 1
    beta: 1
    lambda0: 0.01
    nu: 5
data:
  geometry: geom.txt
  initial_templates: null
  recordings: data.bin
  root_folder: ./
deconvolution:
  deconv_gpu: true
  template_update_time: 300
  threshold: 50
  update_templates: true
detect:
  threshold: 0.5
neuralnetwork:
  apply_nn: true
  denoise:
    filename: denoise.pt
    filter_sizes:
    - 5
    - 11
    - 21
    n_filters:
    - 16
    - 8
    - 4
  detect:
    filename: detect.pt
    n_filters:
    - 16
    - 8
    - 8
  training:
    input_spike_train_filname: null
    spike_size_ms: null
preprocess:
  apply_filter: true
  dtype: float32
  filter:
    high_factor: 0.1
    low_pass_freq: 300
    order: 3
recordings:
  clustering_chunk:
  - 0
  - 300
  dtype: int16
  final_deconv_chunk: null
  n_channels: 10
  sampling_rate: 20000.0
  spatial_radius: 70.0
  spike_size_ms: 5
resources:
  generate_phy: 0
  gpu_id: 0
  multi_processing: 1
  n_gpu_processors: 1
  n_processors: 2
  n_sec_chunk: 10
  n_sec_chunk_gpu_deconv: 5
  n_sec_chunk_gpu_detect: 0.5
