data:
  # project's root folder, data will be loaded and saved here
  # can be an absolute or relative path
  root_folder: data/
  # recordings filename
  recordings: neuropixel.bin
  # channel geometry filename
  geometry: neuropixel_channels.npy

recordings:
  # precision of the recording – must be a valid numpy dtype
  dtype: int16
  # recording rate (in Hz)
  sampling_rate: 30000
  # number of channels
  n_channels: 10
  # channels spatial radius
  spatial_radius: 70

# TURN ON/OFF MODULES
doFilter: True
doTriage: True
doCoreset: True
doWhitening: True

methods:
  # 'nn' for neural net detction, 'threshold' for amplitdue threshold detection
  detection: threshold
  # 'MFM' for mixture of finite mixture clustering, 'dpmm' for dirichlete process mixture model
  clustering: MFM

# PREPROCESS
portion: 1
# max. memory allowed for loading recording (in bytes)
maxMem: 1000000000
# [0,1] to use parital data to estimate templates
partialDat: 1
# determine whitening matrix in each minibatch
whitenBatchwise: 0
# number of features for dimension reduction
nFeat: 3
# temporal length of wavforms in ms
spikeSizeMS: 1

# TRIAGE
# Num. of nearest neighbors to consider
triageK: 20
# percentage of data to be triaged
triagePercent: 0.01

# CORESET
# Num. of clusters
coresetK: 10
# distance threshold
coresetTh: 0.95

# CLUSTERING
# Masking threshold
maskTh: [0.9, 0.5]
# Num. of new clusters in split
kSplit: 5

# TEMPLATE MERGING
# threshold for template merge
tMergeTh: [0.8, 0.7]

deconvolution:
  rank: 3
  threshold: 4
  lam: 20

# Neural network parameters
neural_network:
  # NN filenames
  aeFilename: ae_31.ckpt
  nnTriageFilename: triagenet1.ckpt

  # NN architecture
  # num. of filters in each layer
  nnNFilters: [16, 8, 1]
  # temporal filter size
  nnFilterSize: [31, 1, 1]  
  
  nnTriageFilterSize: [8, 16]  
  
  # NN training
  # train nn and save
  nnTrain: 0
  # 'recording' : raw recording,
  inputType: 'recording'
  # 'sorted_recording' : raw recording with spike train, 'templates' : templates
  # 'rectangular', 'non_rectangular'
  ChannelGeometry: 'rectangular'
  # num. of iter. in training
  nnIteration: 100000
  # size of minibatch in training
  nnBatch: 256
  # training step size
  nnTrainStepSize: 0.001
  # L2 reg. scale
  nnL2RegScale: 0.00000005


# optional
neural_network_detector:
  # model name, can be any of the models included in yass (detectnet1.ckpt),
  # a relative folder to data.root_fodler (e.g.
  # $ROOT_FOLDER/models/mymodel.ckpt) or an absolute path to a model
  # (e.g. /path/to/my/model.ckpt)
  filename: detectnet1.ckpt
  # Threshold for spike event detection
  threshold_spike: 0.5
  # Threshold for clear/collision detection
  threshold_collision: 0.75


# optional
cluster_prior:
  beta: 1
  a: 1
  lambda0: 0.01
  mu: [[0], [0], [0]]
  nu: 5
  V: 2

# optional
filter:
  # Order of Butterworth filter
  order: 3
  # Low pass frequency (Hz)
  low_pass_freq: 300
  # High pass factor (proportion of sampling rate)
  high_factor: 0.1