optional_sections:
  cluster_prior:
    beta: 1
    a: 1
    lambda0: 0.01
    mu: [[0], [0], [0]]
    nu: 5
    V: 2

  filter:
    order: 3
    low_pass_freq: 300
    high_factor: 0.1

  neural_network_detector:
    filename: detectnet1.ckpt
    threshold_spike: 0.5
    threshold_collision: 0.75

  triage:
    nearest_neighbors: 20
    percent: 0.01

  coreset:
    clusters: 10
    threshold: 0.95




fields_validator:
  recordings:
      dtype:
        type: str
      sampling_rate:
        type: int
      n_channels:
        type: int

  methods:
    detection:
      values: ['threshold', 'nn']
      type: str
    clustering:
      values: ['MFM', 'dpmm']
      type: str

  neural_network_detector:
    filename:
      function: expand_asset_model
      type: str
